import grpc
import time
from concurrent import futures

# Import the code generated by the protoc compiler
import snow_removal_pb2
import snow_removal_pb2_grpc

# Import verified logic from the previous steps
import data_utilities as utils

class RoadMonitorService(snow_removal_pb2_grpc.RoadMonitorServicer):
    def StreamConditions(self, request, context):
        """
        Receives coordinates, fetches live data, and yields a continuous 
        stream of updates back to the Scheduler.
        """
        print(f"Stream initiated for: {request.latitude}, {request.longitude}")
        
        # In a production environment, this would be a continuous 'while True' loop.
        # We simulate 5 updates to demonstrate the streaming capability.
        for i in range(5):
            if not context.is_active():
                print("Client disconnected. Terminating stream.")
                break
                
            # 1. Fetch live data using your dynamic bounding box logic
            traffic = utils.fetch_traffic_data(request.latitude, request.longitude)
            weather = utils.fetch_weather_data(request.latitude, request.longitude)
            
            # 2. Determine road priority based on your business logic
            road_type, priority = utils.calculate_priority(
                traffic["frc"], 
                weather["snow_depth_cm"]
            )
            
            # 3. Package the weather data into the Protobuf structure
            weather_msg = snow_removal_pb2.WeatherData(
                temperature_c=weather["temperature_c"],
                wind_speed_kmh=weather["wind_speed_kmh"],
                snow_depth_cm=weather["snow_depth_cm"]
            )
            
            # 4. Construct and yield the final RoadConditionUpdate message
            yield snow_removal_pb2.RoadConditionUpdate(
                road_type=road_type,
                dispatch_priority=priority,
                traffic_speed_kmh=traffic["current_speed"],
                weather=weather_msg
            )
            
            print(f"Update {i+1} sent to client.")
            
            # Pause to respect API rate limits and simulate real-time monitoring
            time.sleep(10)

def serve():
    """Initializes and starts the gRPC server."""
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    snow_removal_pb2_grpc.add_RoadMonitorServicer_to_server(RoadMonitorService(), server)
    
    # Listening on the standard gRPC development port
    server.add_insecure_port('[::]:50051')
    server.start()
    print("Extraction Module gRPC Server is active on port 50051...")
    server.wait_for_termination()

if __name__ == '__main__':
    serve()