# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snow_removal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'snow_removal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12snow_removal.proto\x12\x0csnow_removal\"8\n\x11\x43oordinateRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"S\n\x0bWeatherData\x12\x15\n\rtemperature_c\x18\x01 \x01(\x02\x12\x16\n\x0ewind_speed_kmh\x18\x02 \x01(\x02\x12\x15\n\rsnow_depth_cm\x18\x03 \x01(\x02\"\x8a\x01\n\x13RoadConditionUpdate\x12\x11\n\troad_type\x18\x01 \x01(\t\x12\x19\n\x11\x64ispatch_priority\x18\x02 \x01(\t\x12\x19\n\x11traffic_speed_kmh\x18\x03 \x01(\x02\x12*\n\x07weather\x18\x04 \x01(\x0b\x32\x19.snow_removal.WeatherData2g\n\x0bRoadMonitor\x12X\n\x10StreamConditions\x12\x1f.snow_removal.CoordinateRequest\x1a!.snow_removal.RoadConditionUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snow_removal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDINATEREQUEST']._serialized_start=36
  _globals['_COORDINATEREQUEST']._serialized_end=92
  _globals['_WEATHERDATA']._serialized_start=94
  _globals['_WEATHERDATA']._serialized_end=177
  _globals['_ROADCONDITIONUPDATE']._serialized_start=180
  _globals['_ROADCONDITIONUPDATE']._serialized_end=318
  _globals['_ROADMONITOR']._serialized_start=320
  _globals['_ROADMONITOR']._serialized_end=423
# @@protoc_insertion_point(module_scope)
