# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from data_layer import snow_removal_pb2 as snow__removal__pb2
except ModuleNotFoundError:
    import snow_removal_pb2 as snow__removal__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in snow_removal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoadMonitorStub(object):
    """The service definition exposing a server-side stream
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamConditions = channel.unary_stream(
                '/snow_removal.RoadMonitor/StreamConditions',
                request_serializer=snow__removal__pb2.CoordinateRequest.SerializeToString,
                response_deserializer=snow__removal__pb2.RoadConditionUpdate.FromString,
                _registered_method=True)


class RoadMonitorServicer(object):
    """The service definition exposing a server-side stream
    """

    def StreamConditions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoadMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamConditions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConditions,
                    request_deserializer=snow__removal__pb2.CoordinateRequest.FromString,
                    response_serializer=snow__removal__pb2.RoadConditionUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snow_removal.RoadMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snow_removal.RoadMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoadMonitor(object):
    """The service definition exposing a server-side stream
    """

    @staticmethod
    def StreamConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/snow_removal.RoadMonitor/StreamConditions',
            snow__removal__pb2.CoordinateRequest.SerializeToString,
            snow__removal__pb2.RoadConditionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
